Use new snyk protect
snyk/add-to-package pull request #10
Opened 2021-06-15 21:15 UTC by maxjeffos

Use the new `@snyk/protect` package rather than the entire `snyk` package.

2021-06-16 09:04 UTC, aviadhahami commented
@maxjeffos should this still be under @snyk/boost ?

2021-06-16 14:25 UTC, jahed-snyk approved these changes

2021-06-16 19:56 UTC, maxjeffos commented on lib/index.js
> +  pkg.scripts['snyk-protect'] = 'npm_config_yes=true npx @snyk/protect@latest"';
Setting the env var `npm_config_yes=true` rather than using `--yes` to be back-compatible with npm@6.

2021-06-17 10:34 UTC, jahed-snyk commented on lib/index.js
> +  pkg.scripts['snyk-protect'] = 'npm_config_yes=true npx @snyk/protect@latest"';
Is that needed? I thought npm@6 doesn't prompt for confirmation? 🤔

2021-06-17 12:08 UTC, maxjeffos commented on lib/index.js
> +  pkg.scripts['snyk-protect'] = 'npm_config_yes=true npx @snyk/protect@latest"';
It doesn't, but with npm@6, if you pass the `--yes` it doesn't work properly:
```
❯ npx --yes snyk@1.605.0 --version
6.14.12
```
That's the npm version, not the snyk version!

So in order to make it suppress the prompt on npm@7 and not cause this weirdness on npm@6, we can set the env var `npm_config_yes` - it is simply ignored by npm@6.

2021-06-17 15:45 UTC, maxjeffos commented
> @maxjeffos should this still be under @snyk/boost ?

@orsagie moved it to loki.

2021-06-17 16:04 UTC, aviadhahami approved these changes

2021-06-18 10:09 UTC, jahed-snyk approved these changes

2021-06-18 13:28 UTC, jahed-snyk commented on lib/index.js
> +  pkg.scripts['snyk-protect'] = 'npm_config_yes=true npx @snyk/protect@latest';
env prefixes don't work on Windows.

2021-06-22 12:27 UTC, jahed-snyk requested changes

2021-06-22 12:27 UTC, jahed-snyk commented on test/npm.test.js
> +  testUtils.assertPackageNotDefined(t, pkg, 'snyk', 'dependencies');
It's difficult to reason about these tests as they're asserting on too many things. Should we move the dependency assertions to their own tests (possibly unit tests for `updateSnykDependency`)?
If we want higher-level input/output package.json tests we can use snapshot testing.

2021-06-22 12:27 UTC, jahed-snyk commented on test/npm.test.js
> +test('already testing moves stays with devDependencies when adding protect but upgrades version', t => {
This sentence doesn't make sense. "moves stays"

2021-06-22 12:27 UTC, jahed-snyk commented on lib/index.js
> +  if (testing) {
Should we move all of the code above that calculates the value of `key` into this `if (testing)` statement? It's all useless outside the scope of this condition.

2021-06-22 12:27 UTC, jahed-snyk commented on test/unit-tests.jest.js
> +const lib = require("../lib/index");
Can we have a test module for each function under test rather than a single large one?

2021-06-22 12:27 UTC, jahed-snyk commented on test/yarn.test.js
>  const { test } = require('tap');
Instead of repeating the entire test suite for every packageManager, should we remove `yarn.test.js` and just have a single test under `npm.test.js` (rename that to be more generic) that ensures we are taking `packageManager` and applying it appropriately?

2021-06-22 12:27 UTC, jahed-snyk commented on lib/index.js
> +  updateSnykVersion: updateSnykDependency,
Why do we rename `updateSnykDependency` to `updateSnykVersion`?

If it's for backwards compatibility, it doesn't look like anyone's using this function outside of this module.

https://github.com/search?q=org%3Asnyk+updateSnykVersion&type=code

Also, since we're releasing a breaking change, it doesn't matter if we change the public interface that much (as long as we document it).

2021-06-22 12:27 UTC, jahed-snyk commented on jest.config.js
> +module.exports = {
`testEnvironment`, `collectCoverage` (and related config keys) are defaults so we can remove them.

https://jestjs.io/docs/configuration#testenvironment-string
https://jestjs.io/docs/configuration#collectcoverage-boolean

2021-06-22 12:27 UTC, jahed-snyk commented on lib/index.js
> +  // update to the new snyk-protect script
Do we need this comment?

2021-06-22 12:27 UTC, jahed-snyk commented on package.json
> +    "jest": "^27.0.4",
How much work is it to migrate the tap tests to jest so that we don't have to deal with fragmentation?

2021-06-23 20:43 UTC, maxjeffos commented on lib/index.js
> +    const protecting = isProtecting(pkg, packageManager);
resolved

2021-06-23 20:48 UTC, maxjeffos commented on test/unit-tests.jest.js
> +const lib = require("../lib/index");
We could, but that wouldn't be in keeping with the test file per module thing.
Let me know if you like how I restructured the tests in terms of file layout.

2021-06-23 20:49 UTC, maxjeffos commented on test/yarn.test.js
>  const { test } = require('tap');
I skipped this because it's a lot of yak shaving at this point and what we have works. If we're going to do that, I'd rather do it in a separate PR so that we aren't blocking releasing protect on it.

2021-06-23 20:50 UTC, maxjeffos commented on package.json
> +    "jest": "^27.0.4",
Yes! But I did it.

2021-06-23 21:32 UTC, maxjeffos commented on test/npm.test.js
>  test('add(protect)', t => {
done

2021-06-24 09:39 UTC, jahed-snyk approved these changes
Left a comment but feel free to merge.

2021-06-24 09:39 UTC, jahed-snyk commented on lib/index.js
> +  return Boolean(protectingScript);
Can use `.some` instead of `.find` to avoid the boolean conversion here.

2021-06-24 09:39 UTC, jahed-snyk commented on test/unit/lib/index.test.js
> +describe("updateSnykProtectDependency", () => {
My original suggestion also involved splitting these functions into their own modules to avoid a large unit test file with multiple responsibilities.

2021-06-24 09:45 UTC, jahed-snyk commented on test/unit-tests.jest.js
> +const lib = require("../lib/index");
I think it is, for readability and separation of concerns. But I'll leave the final decision up to you.

2021-06-24 13:40 UTC, aviadhahami approved these changes

2021-07-14 12:40 UTC, merged